env:
  commonjs: true
  node: true
  es6: true
  jasmine: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2018
  sourceType: script
rules:
  no-console: 'off'
  no-unused-vars: 
  - "error"
  - { "argsIgnorePattern": "^_" }

